### PR TITLE
Detector prototyping board

### PR DESCRIPTION
**Pull request by LanaTomlin**
HI 

The overall schematic should be good to go. ERC is giving me some errors that I Do Not Understand and I need to fix that but I am tired and thus am probably gonna do it tomorrow.
Makn' this pull request a bit early in hopes to (maybe) get some reviews whilst I figure out the ERC errors.

Thank you for your time,
a dumbass who may or may not light things on fire for fun

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020/11)

### CODE REVIEW

**Review by rdakhil — COMMENTED** [review]
1. As Lance mentioned for papa board, there doesn't need to be a voltage divider on the MISO line since it's already running 3.3V logic out of the SD card 
image

2. power_supplies sheet seems to be missing

3. As was also suggested on papa board, you should remove the hierarchical pins on the detector circuit sheets. It's also causing some ERC warnings since there aren't any corresponding hierarchical labels inside the detector sheets.
image

4. Might just be on my end, but it seems like some components are not on the same grid. I fixed this on papa board by making sure the grid is set to 50 mils on all sheets AND symbols. If you press "m" on a misaligned symbol it should move onto the grid automatically, but unfortunately you'll have to re-do all the wiring connected to that symbol since the wires will also be misaligned.

6. What's the part number for D6?
image

7. Really minor, but some text is overlapping in the detector circuit sheet
image

8.  Again this is minor, but the comparator circuit overlaps with the title block. You can make it fit without any overlapping by re-arranging the sheet like this:
image

9. U1 and U3 are missing pin numbers which will cause some ERC errors

10. Why is the boost converter connected to both battery and 5V? This configuration was designed for 12-16V input so it won't work with 5V. Values for C7, R11, F1, and F2 are also missing on the boost converter, and R14 should be 470k ohms, R15 should be 16.2k ohms. I would also suggest connecting 5V to the enable pin, since that is being turned on/off by papa board and i dont think we want the boost to always be on.
image
Also why is it on this board along with the 5V and 36V LDOs if they're all on papa board?

**Comment by LanaTomlin** [comment]
okay to address a couple things:
this isn't what's going on the rocket, this is a test prototype board. that's why there's two power sources. and why there's a bunch of power infrastructure we didn't have before. the mama_board schematic shouldn't be in this pull request, going to try to remove it. 
The two connectors are so we can test both with and without lipo batteries. and becauSE we REALLYY don't want both pwer supplies on at the same time i just popped a couple extra fuses on there just IN case

the grid stuff is valid but i don't want to fumble around fixing that right now, so i'll slowly try to fix things as i go, but yeee.

**Comment by zx100x100** [comment]
Added a proper level shifter to the SD card miso line, added / moded a few jumpers.

**Comment by ZTeper** [comment]
image

image


Just a friendly reminder that the RC filter frequency is given by the formula f = 1/(2*pi*R*C)

**Comment by ZTeper** [comment]
image

Which values to use for R and C?

**Comment by ZTeper** [comment]
image

image

This is a power module, not a chip. Also, it is a buck converter, not a linear regulator. Please replace U1.

**Comment by ZTeper** [comment]
image

Shield should be grounded

**Comment by LanaTomlin** [comment]
the 5V regulator is buck/boost on purpose - our systems is, legitimately enormous at this point, and we don't want to sink a whole bunch of power into heat by using a linear regulator :)))

we did change it anyways 'cause the component was too big

**Review by BluCodeGH — COMMENTED** [review]
I don't really know what I'm doing but I noticed a few things you might want to take a look at:
1. You seem to mix between B.SilkS and Dwgs.User for the LDO text/outlines.
2. The lowest silkscreen outline for the 37V regulator isn't straight. It also overlaps a via or two.
3. Some of the test point positions seem a little odd (eg under a microcontroller)
4. The SD card silkscreen outline overlaps the Q1 text.
5. The silkscreen outline for the 3V3 U4 is on the wrong side.
6. Check out the Cmts.User layer lol
7. There are some more instances of silkscreens intersecting pads on the back.
Overall things seem really cramped to me, especially on the backside where you have so much unused space, but also on the front it seems like stuff could be shifted around a bit so there's a bit of breathing room between components.

**Review by dwkletke — CHANGES_REQUESTED** [review]
Like Jack mentioned, overall the back of the board is more tightly packed so some more thought could go into this area to space it out when tracing. However, considering this is just a prototype it shouldn't be too much of an issue overall. If this PCB size is already pre-determined then you should have _plenty_ of space for everything! Some more specific comments:
-  Generally speaking, it's good to have the CAN connector (J2) as close to the edge of the board as possible. [NITPICK]: Speaking of J2, the silkscreen for J2 is inside the connector square and will hard to read when the part is on.
image
- If you want to read the silkscreen names for the connectors when they have cables plugged in, it will be difficult to read them when they are on the edge of the board (if they are 90 degree connectors, however if they are top-down then it shouldn't be an issue).
image
- Silkscreen here is overlapped (however note, this is really nitpicky since your silkscreen placement with probably change with tracing).
image
- I am assuming you are still moving some of these headers? They go right through C15.
image
- These components are probably a bit close together for soldering them/the MCU (also if they need to be desoldered), although not super important if skilled with an iron :)
image
- [NITPICK]: Also, for reference, the board outline/layout is at the edge of the page and should probably be centered.
image
- Overall, this section is really cramped with multiple silkscreens overlapping. Could probably use more of the back side of the board to space out components for easy soldering.
image
- If these circles are supposed to be the mount holes, you should probably just add them in as such.
image

Overall, more layout-specific comments will probably arise from tracing which I would recommend commencing as soon as possible since that is where the more in-depth review will be required.

**Comment by LanaTomlin** [comment]
SO THE reason all the green stuff is so close together is because it's super sensitive analog circuitry, and i wanna minimize with trace capacitance/resistances

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
It seems that most of the stuff to address has been pointed out by others, but I'll point out some stuff that (hopefully) hasn't been mentioned already.

image
It seems that there's a few components hanging out and about over here.

image
Seems to be some overlapping labelling

image
What's this circle over here? It seems like it fits the hole on the opposite side but it's nowhere near?

image
A few things with the silkscreen labelling on the back of the board - issues include: overlapping, backwards text, and (for the bottom-right) inconsistent formatting of the labelling -- only this label is bolded. I think the `R27` label can be beside `R28` like the row above

image
What's this line over here? 

Additionally, I think it may be worth rotating all the silkscreen labelling so they're all rotated the same way, whenever possible.

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
I'm seeing quite a few errors being spat out by the Design Rules Checker, including 3 unconnected items. Please take a look at them and see if you can get them sorted out.

**Comment by LanaTomlin** [comment]
image
So there are some unconnected pads on the PIC18, this is because the netlist is messed up.
MOSI and MISO are somehow connected on the PCB, when they are not connected on the schematic.
On the image above, both pin 13 and 15 are labelled as "MISO", while on the schematic:
image

They are not attached.
We weren't able to fix the problem, so we just routed them manually. 
woooot

**Review by BluCodeGH — COMMENTED** [review]
<Usual disclaimer that I don't know nearly enough about PCBs to determine if these need to be fixed>
1. Daisy chaining in C21, C23, C13, C14, R41, C20, R23, C11, R15, L1, U2, C33, C39, maybe other places too?
2. Trace width weirdness with +BATT near U1
3. Weird via placement for the leds, why not keep them in line?
4. What's going on with the trace right above U6?
5. Double ground vias to the left of U6
6. Weird trace on the bottom pad of R13, left of C4 (why not straight) and top pins of U2 (I noticed a few other less sever cases you could look for if this needs fixing).
7. The left pad of R29 has a trace running through it.

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Yeah, as above comment says, take a look around and try to get rid of any daisy-chaining that exists.

Hopefully you can figure out where these pictures are based on the labels in the screenshot, but I reviewed the board in roughly a clockwise path if that helps

image
Could these vias just be moved onto these traces instead of having their own traces leading to them?
image
Straighten up this trace like the one beside it? Additionally, could use a via to get rid of the messiness of routing around CANH
image
Not too sure about how it would affect things electrical-wise, but could we just hook up the header to ground through this via instead of a separate one?
image
Not sure how this would affect Y1, but use the same GND via for both these caps?
image
Seems to be a bit of trace width inconsistency here
image
Some more trace width funkiness (left). Could we straighten up this trace (right) so we can get rid of that teeny notch?
image
I get the ground vias under U6, but two vias here?
image
Worthwhile for all these to just be hooked up to one via?
image
(top) - why not a straight line from one pad to the other?
(bottom) - hook up C12 from the via instead of daisy-chaining through R-15?
image
(left) - Pop the via in between the two pads and make the trace a straight line (through the via) from one pad to the other?
(right) - Straight line from one pad to the other?
image
Some more vias to move/combine and prettify if desired
image
More vias to combine if desired
image
Traces around the via looking a tad odd here
image
(bottom) - Combine vias if desired
(top) - a bit of irregularity on the trace widths it seems

I am not too familiar with the electronics behind this board so please disregard any proposed changes to things that exist for a reason, and preferably let me know so I can understand how the zappy stuff works just a bit better.

**Comment by LanaTomlin** [comment]
Okay so a bit of that daisy chaining is on purpose, a some of those caps (C21, C23, C20, C11, C39) are decouplers, and the point is that we want to make sure current goes through the caps before it goes into the chip
image
From what I can tell C13 and C14 should be decouplers as well, but fill sensing doesn't have 'em daisy chained, so I won't either. 
(They could actually use MORE daisy chaining on the ground plane

For R41, we're following this schematic as closely as possible:
image

And it has those guys chained. 
(also chucking the 37V diagram in here for good measure)
image
More explanations to come, im tired and going to sleep

**Comment by LanaTomlin** [comment]
Okay so on @QuantumManiac's comment- 
"(top) - why not a straight line from one pad to the other?"
For visability! we want to be able to see that they're connected on the physical PCB

"(bottom) - hook up C12 from the via instead of daisy-chaining through R-15?"
That's because it's a decoupling capacitor, and they're more effective that way. (See comment after Jack's review)

"Traces around the via looking a tad odd here"
The DET ADC line is a fairly sensitve analog line, and we want it to be THICCCC to reduce resistance (This is why all the power lines are also thiccer traces than anything else) I've actually now turned that guy into a polygon :))


ON THE VIAS:
We want MORE VIAS. vias are GREAT because they give better thermal performance as well as increse the resistnace of the trace (big copper pour on a different layer)
I do a bit to make the vias prettier tho

**Review by dwkletke — DISMISSED** [review]
Overall this looks really good. Just a few general comments:
- Whenever possible, label the dimensions of the board :)
- Where have the mounting holes gone!!!! Is this prototype not going to be mounted anywhere?
- There are quite a few components _very_ tightly packed on this board that I am a little worried about for soldering purposes. The discretion is up to you if you don't see an issue based on your soldering abilities. Note: I am also mentioning this because you have so much space on this board!!!!!
image
image
image
- Nit: The `TEST_CONN` silkscreen is backwards compared to the rest of your silkscreens
image
- I think I mentioned this earlier but the CAN connector _should_ be as close to the edge of the board as possible. This might give you a bit of pain in the future but really not too big of an issue.
image
- If I am misunderstanding something (a very real possibility - it's late), what is the reason to have these through-hole pins connected to the GND pour with vias? Aren't they already connected on that pour from the pin's themselves? I don't think the extra via or two will provide much but idk :/
image
image
image
image

- Is there a reason you are running the ICSPCLK and ICSPDAT traces/vias longer by going outside the silkscreen? Vs. having them in under the PIC?
image
- Last note: Don't forget to add your name and the WR logo when you are close to done with routing :)

**Comment by rdakhil** [comment]
As mentioned in our group DMs, you'll need differential pair routing for the CAN and CAN lines from the transceiver to the connector 
image

Not sure how important this is (I am still very unexperienced), but I would follow the PIC datasheet for the layout/routing of the oscillator
image
image

C22 on the 5.3V regulator should be on the other side of the buck and connected to the battery like in the datasheet, this will also allow you to have the 1u capacitor closer to the buck which is ideal image
image

In the peak detector circuitry, not sure how important this is because they are the same net but the pad and the trace are touching on C19: 
image

Hard to see, but there is a 90 degree angle here below the SD card: 
image

Nitpick, but there is an unconnected trace here that makes an awkward blob on the edge of the of the polygon
image

**Review by JaredWatson — CHANGES_REQUESTED** [review]
There's some uneven spacing here
image

There's some silkscreen that looks a little close to components and pads, I'll let you get another commit before I pick on all of them. You have lots of room on this board, dont be afraid to use it to make silkscreen easier and hand soldering that much nicer.
image

I lied, here's one I want to make sure gets caught. Make the REF** designator hidden or on a notes layer
image

It would be nice to get some colour marker on the schematic/PCB of the colour of the LED so a programmer looking at the schematic and an assembler can easily tell which diode goes where. If they're all red, might as well mark them all red so it's clear.
image

Adding on to Dawson's comments, it's also nice to leave some instructions on the notes or even fab layer on DNP parts (like your 0R resistor comment) just so it doesnt get missed (though I dont think we're having these boards assembled with a pick and place are we?)

Again I'm on this one late, so thanks for the detailed comments you already addressed like 1/2 my review comments :P. If you have any high frequency signals let me know and I'll go over those areas much more strictly but overall a very nice board, I like the person touch too.

**Comment by LanaTomlin** [comment]
@JaredWatson 
image
this section doesn't have SUPER high frequencies, but it has a pretty fast signal spike & sensitive analog circuitry, if you're willing to look at it w/a fine tooth comb

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
It seems like the mounting holes disappeared. Did you accidentally delete them while you were deleting their `REF**`? 
image
Additionally, wasn't there a logo here?
image
There seems to be a measurement on the silkscreen layer over here
image
Tiny kink that you could probably straighten out here
image
Not sure if it matters, but there's a tiny bit of silkscreen off the board here. Could shift this component a tad to the right if desired.
image
My DRC settings might be off but I got a "track too close to pad" over here

That's all I could find (for now) that hasn't already been mentioned. Cool stuff!

**Comment by amihaila** [comment]
> It seems like the mounting holes disappeared. Did you accidentally delete them while you were deleting their REF**?

Any footprints that aren’t in the schematic and also aren’t marked as locked will get yeeted next time you reimport the netlist. You can get around this by marking those footprints as locked.

**Review by zx100x100 — CHANGES_REQUESTED** [review]
after many moons; my review:

1. Don't use 0 to indicate DNP, I guarantee someone will short your board with a zero ohm resistor
2. This is a completely separate piece of hardware, detector proto should be it's own folder and project name, cause it will get merged with mama at some point.
3. do you need net labels here? I spent like 30 seconds looking for the connections, would be nicer if it was wired
image

4. Quesadilla le fcuk
image

5. MORE LEDS (you have space for 3 debug LEDs 3 is a nice number)

6. Lable your connectors as much as possible
image

7. Label your MCLR line, including voltage

**Comment by JaredWatson** [comment]
More of a nit and for future reference (dont need to fix now since its functionally equivalent but a style thing). These are the same node, theres not too big of a reason to name them twice.
image

During the review we talked about why there were two copies of the bandpass. The answer was in case of errors during bringup.
image

SIPM is "HF" (if anyone can even define what a high frequency is) so make sure to keep them as short and as wide as possible, consider moving U12, C35 down to make the trace as short/straight as possible and then make the trace larger if possible.
image

We discussed these silkscreen vias and determined they were accidental, pls remove
image

The silkscreen here is a little close, consider moving J9 to make it more clear they're different text
image

The silkscreen for U13 is closer to JP1 than it is to its own component here
image

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
image
Is this bit of the trace supposed to be missing?

image
DRC is complaining about this missing connection, but I'd imagine that it can be hooked up without a trace?

Taking a look a the `gerbers` folder, there seems to be a few useless empty zip files. Could probably clean that up. Additionally, the zip file that actually contains the gerbers is named `detector_circuit-F_SilkS.zip`. Could be changed.

The current state of the gerbers seems to be fine though. Everything seems to have generated nicely.

**Comment by QuantumManiac** [comment]
Review on `detector_circuit_LTC6269`

image
Something seems to be funky with this zone - DRC is majorly complaining about overlapping copper areas.

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Review time:

1: might be necessary, but oh man so many PCBs and project files, maybe some folders?:
image

2. DRC is listing a few disconnected nets on the main board, please fix.

maybe add a really quick Readme to really roughly explain what's happening here? I'm not really sure which of these 6 projects I need to review

**Comment by LanaTomlin** [comment]
README

So this is the protoboard for the detector circuit. It's split up into two parts, all the supporting infastrucutre (detector_support), and the actual detector circuit, whose file names are named after the op amp that each of them uses. ( detector_circuit_LTC6269.sch, detector_circuit_LTC6254, detector_circuit_alt_LTC6254). 


Each of the detector circuits connect to the support board with the circles components:
image

And both the disconnected nets are very much on purpose, SiPM_Out is connected on the detector_circuit boards and there's no point in connecting it on both PCBS.

**Comment by ZTeper** [comment]
If the two nets are meant to be disconnected, please give them distinct net labels in the schematic so that the DRC is not confused.

Also, some of your surface mount components are really close together and will be quite painful to solder by hand. Are we planning to use the reflow oven for this? Try spacing things out a bit more.

image

This is a hand-soldering nightmare.

**Comment by ZTeper** [comment]
image

image

**Comment by ZTeper** [comment]
image

Youve got a silkscreen line cutting straight through a mounting hole. Is the mounting hole in the right position? Consider different lines/shapes for your slikscreen.

**Comment by ZTeper** [comment]
image

Please align the pin labels with their respective pins

**Comment by ZTeper** [comment]
image

Are all these vias really necessary?

**Comment by ZTeper** [comment]
image

Hmmm...

**Comment by LanaTomlin** [comment]
the MISO-MOSI net is fucked up which is why that one is disconnected. They do have different names on the schematic, no idea why kicad thinks the net needs to be connected on the PCB.

As for the hand soldering, I am very aware it's going to be a pain in the ass, but I'm confident in my soldering abilities, and I would rather keep the sensitive DC converter layout as close to the datasheet image as possible. 

The vias are probably overkill but, just following the datasheet with that one. Better safe than sorry. 
mounting hole is in the right position. I was just in more of a rush to get the important stuff done than fiddle with a little bit of line.

**Comment by ZTeper** [comment]
image

Putting silkscreen on top of solder pads is unadvisable. Please interrupt your thick line to make space for your diodes

**Comment by ZTeper** [comment]
image

Please move your "5V" silkscreen away from the solder pad.

**Comment by ZTeper** [comment]
image

I dont like being a stickler about things but please fix the silkscreens touching solder pads.

**Comment by ZTeper** [comment]
image

Random silkscreen blobs floating in space

**Comment by ZTeper** [comment]
image

Missing mounting hole ???

**Comment by ZTeper** [comment]
image

Random line segment ???

Please adjust dimensions to match the actual board size.

**Comment by ZTeper** [comment]
image

DRC is unhappy; please fix copper zones

**Comment by ZTeper** [comment]
image

The AMP_OUT trace is nearly connected; please connect the via to the trace properly.

**Review by zx100x100 — APPROVED** [review]
Looks good, conditional approval based on you fixing the critical things. also tiny things that bother me:

this bothers me a lot:
image

Failing to pass DRC bothers me, but that has been explained so oh well

A few places where the silkscreen goes over pads, this needs to be fixed sorry :sadparrot:
image
this isn't all of them but it's the worst part.

alt_LTC6254 looks good!

needs fixing at some point:
image


same issue on the LTC6254.

dates?

otherwise  LTC6254 looks good


I'm afraid you might fail EGAD
image


Otherwise LTC6269 is good!

**Review by JaredWatson — APPROVED** [review]

**Review by QuantumManiac — APPROVED** [review]
Since it's ordered, I think this can be merged now.

**Pull request merged**
