### PR TITLE
Mama board

### PR DESCRIPTION
**Pull request by rdakhil**
Added power management

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020/10)

### CODE REVIEW

**Comment by LanaTomlin** [comment]
where did the pic18f sheet go

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Alas my review, sorry for the delay:

1. You have the 5V pin of the CAN bus attached to the 12V pin, this is bad for hopefully obvious reasons
image

2. your schematic is not fully annotated, please fix this
3. Please go through the detailed design calculations on page 14 of the MC33063AP datasheet and confirm the values selected from the example application circuit line up with what you actually want. For example are you happy with 40mVpp noise after the filter? seems kind of high, or are you actually planning to draw 175mA? 
image

4. the PIC18F26K83 sheet doesn't exist, makes it kind of hard to review lol

**Comment by LanaTomlin** [comment]
*********************REVIEW FROM LANCE******************************88
General comments
Get rid of + on voltage rails - it’s unnecessary 
Voltages should be in this format (standard in industry): 5V0, 4V7. 36V6, 36V0, 12V0
Move 5V to 4.7V LDO should be on mamaboard
Voltage drop bc of wires
One less connection on the connectors (4.7V)
Does not make sense to send 5V, 12V, 36V, AND 4.7V from one board to another
Use manufacturer product number on ALL ICs/connectors/inductors/diodes (NOT passives like resistors and capacitors)
Note max Iout rating for every power supply (LDOs and SMPS) on the schematic
Make sure all parts are annotated 

Battery connector
Every connector should have manufacturer product number
Fuse doesn’t have enough information on the schematic  -> current rating of fuse
JP1 - Jumper useless
D1 - Diode wastes a lot of power. Not ideal method for reverse polarity protection
(+11-16V Dirty) should be a voltage rail VBATT
Put lipo text in top right corner
Remove “dirty”
11V is actually 12V - check lithium ion voltage curve

System Sleep Control
PMOS currently doesn’t do anything since it’s connected to a jumper that goes to an unconnected net.
What controls PWR_EN signal?



5V -> 4.7V LDO
Max 150mA LDO
On/off switch - where is it switched? Will this LDO ever need to be turned off?
Consider having the LDO always on. 
Pull INH high to VIN (5V)




PIC and pro 
SPI chip select signal requires a pullup resistor
Part number incorrect U6 and U7
Manufacturer product number is incorrect. MCP2562-E-SN -> MCP2562-E/SN
MCP2562-E/SN is out of stock on Digi-Key
VIO and VDO pins each need a separate decoupling capacitor
Read datasheet
Crystal has insufficient information 
Need to know frequency and manufacturer product number
Important so schematic reviewer can verify the load capacitor calculations
Make sure all parts are annotated
Best practice: net names should be ALL CAPS

Battery management sheet
VBATT net label
Rotate U4 90 deg, fix symbol to look like U3
Rated 1.5A
Again, note the max Iout for every power supply on the schematic
*****************************************************************************

**Review by LanaTomlin — COMMENTED** [review]
Potatoes left to fry here:
1. Add PIC18F26K83 and MCP2515 
2. Add interrupt and ADC connections
3. Change anything required by testing

**Pull request merged**
