### PR TITLE
new schematic pdf for review

### PR DESCRIPTION
**Pull request by pauladam316**
pls review schematic Payload2020_base_board.pdf

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020/1)

### CODE REVIEW

**Review by akmorrison — CHANGES_REQUESTED** [review]
First things first, I'd highly recommend adding .DS_Store to your gitignore file. Secondly, please don't have a file called Payload2020_BaseBoard.pdf and another called Payload2020_base_board.pdf. If it's a historical thing, just delete the older one, it's in git, it's ok.

Mistakes I see:
- D1 and D6 are driven by the same net, LED2. You probably meant LED1 for one of them.
- You have jumpers (JP3,8,16,17) so that the arducam can be driven by either arduino (I think), but the slave select pin (SS4) is only wired to one of them.
- Similarly, only arduino 2 is wired into the valve shutdown/enable pins, so it isn't possible for arduino 1 to control that. What is your goal with having the two arduinos exactly?
- I've seen conflicting reports on the internet on whether SD cards need a pullup resistor on the MISO line. I opted to put one there on logger, and that works, so you might need to do some research
- On valve control, you're tying a pin that's pulled up to 12V into a microcontroller pin. This doesn't work, you either need an N-mos tied to that pullup resistor (R16) or you should do low side switching on the valve. Right now that valve will always be active.

Questions I have:
- What is the goal of having 2 arduinos? Are you sharing computation or adding experiment redundancy?
- Why are you using 2 hex buffers, but only using three of the 6 available pins? Just use one of them

Aesthetics:
- You have two almost identical top level circuits (arduino->(sd card, can, LED)), maybe make those hierarchial sheets. This'd avoid errors like the LED1/2 thing above
- Way too many net labels on the top level sheet, it's almost impossible to read
- Similar to above, please put pullup resistors near the things they're pulling up. It's really confusing to see what all is and isn't pulled up

**Comment by pauladam316** [comment]
What is the goal of having 2 arduinos? Are you sharing computation or adding experiment redundancy?

I'm a little concerned about running out of space and processing power on the sole arduino so I was going to add a second just for the Arducam, but I figured fuck it, make it a separate system. So the current design has the leftmost arduino handling the SiPM experiment and the right one handles the cloud chamber. Both arduinos can control a few things so if we have problems down the line with processing speed or storage, functionality of one can be offloaded to the other. But as it currently stands they are independant redundant experiments, only sharing a power supply

Why are you using 2 hex buffers, but only using three of the 6 available pins? Just use one of them
I copied it from an adafruit breakout. You're right, I could but I'm lazy

I've seen conflicting reports on the internet on whether SD cards need a pullup resistor on the MISO line. I opted to put one there on logger, and that works, so you might need to do some research
I'm going to say no, since the adafruit guide for SD breakouts says no

**Comment by pauladam316** [comment]
> D1 and D6 are driven by the same net, LED2. You probably meant LED1 for one of them.
Fixed

> You have jumpers (JP3,8,16,17) so that the arducam can be driven by either arduino (I think), but the slave select pin (SS4) is only wired to one of them.
arducam is only supposed to be driven by A2

> Similarly, only arduino 2 is wired into the valve shutdown/enable pins, so it isn't possible for arduino 1 to control that. What is your goal with having the two arduinos exactly?
A1 controls the SiPM experiment and A2 controls the arducam. They have a linked i2c bus so I can offload some processing from A2 to A1 if need be.

> I've seen conflicting reports on the internet on whether SD cards need a pullup resistor on the MISO line. I opted to put one there on logger, and that works, so you might need to do some research
I don't think its necessary based on tutorials I've found online for arduino

> On valve control, you're tying a pin that's pulled up to 12V into a microcontroller pin. This doesn't work, you either need an N-mos tied to that pullup resistor (R16) or you should do low side switching on the valve. Right now that valve will always be active.
Replaced with a low side nmos, current is low (50mA) so the fact that it will be only part on is fine

> Why are you using 2 hex buffers, but only using three of the 6 available pins? Just use one of them
This was a mistake on my end, but I did the routing for it before I saw your comment so I don't think its worth the effort to fix. IC's are cheap


>You have two almost identical top level circuits (arduino->(sd card, can, LED)), maybe make those hierarchial sheets. This'd avoid errors like the LED1/2 thing above

>Way too many net labels on the top level sheet, it's almost impossible to read

>Similar to above, please put pullup resistors near the things they're pulling up. It's really confusing to see what all is and isn't pulled up

The way I generally try to design schematics is such that they have a nice visual flow. The main rules I generally try to follow for schematic design are
Inputs on the left, outputs on the right, power management on the top
connectors should be in the top level schematic
the main circuit logic of the board (in our cases generally the MCU) should be in the top level schematic
I think following these rules makes for more readable schematics in that you can see from the top level schematic what goes into the circuit, what comes out, and what is the main purpose of the schematic. You were right in your PR comments that mine could use a bit of work so I changed it up a bit. I removed a lot of the net labels, brought pullups to the pins they pull up and rearranged things to give it a better visual flow. I didn't take your suggestion of moving the Arduinos into hierarchal sheets because of my rule 3. While yes this does mean i have some duplicate circuits I enjoy the readability it provides.

**Comment by pauladam316** [comment]
Layout is also up if you want to have a look at it

**Comment by akmorrison** [comment]
> Replaced with a low side nmos, current is low (50mA) so the fact that it will be only part on is fine

Not exactly sure what you mean by "part on". You're gonna be driving this mosfet all the way into triode, it's all the way on. You can reduce the Rds by increasing Vgs more, but with standard mosfets, the Rds at 5V Vgs is fuckall, especially if you only need 50mA of current:

Here's a 15 cent mosfet with typical Rds of 3 ohms at 50mA iD, 5V Vgs (compared to your 240 ohm valve)
https://www.digikey.ca/product-detail/en/nexperia-usa-inc/2N7002NXAKR/1727-8643-1-ND/10416560

**Review by akmorrison — APPROVED** [review]
Only thing left to fix is the floating LED1 net thing.

I still think you can remove one of the Hex buffers to save BOM cost and board space, but if it doesn't matter you're probably good

**Review by amihaila — APPROVED** [review]
I don't see any critical problems.

**Comment by jacobdeery** [comment]
What is the status of this PR? @pauladam316 @zx100x100

**Pull request closed without merging**
