### PR TITLE
Mama Board Hardware

### PR DESCRIPTION
**Pull request by rdakhil**
Mama board schematic is finished, based on protoboard with some adjustments.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020/13)

### CODE REVIEW

**Comment by MattiGen** [comment]
Why do we have 3 GND pours? Not saying it's wrong, just curious

**Comment by MattiGen** [comment]
image
Slight silk screen overlap

image
Why is this trace so chunky, this happens in a couple places.

image
Fill out this trace, why does it taper?

image
Some daisy chaining here on that 36V pad.

image
More daisy chaining through the via.

**Comment by MattiGen** [comment]
image
Why is this like this? Also it's large enough that thermal protection may be an issue.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
1. Daisy chain on C13, C2, C5, C31, C17, C15, TP2, TP4, TP6, C21, C23, C27, C29
2. The whole lower left half of your +36V pour is barely connected to the rest
3. You don't need ground traces across ground pours, eg around U10. You can use the highlight net feature in kicad to spot these.
4. Watch out for silkscreen that overlaps vias, eg C5
5. I think in general fills are detracting from the readability of this schematic, your copper is all sorts of weird shapes (take a look between R34 and R35). That's definitely not actionable though lol

(pls review https://github.com/waterloo-rocketry/daq/pull/13)

**Comment by rdakhil** [comment]
The ground pours on the outer layers aren't strictly necessary, but I put them there because I heard it helps dissipate heat, keep the cooper balanced which prevents warping of the board, and reduces EMI.

All other review changes have been made, although I will double check my work tomorrow (and review briefcase power board). Thanks!

**Review by BluCodeGH — APPROVED** [review]
LGTM!

**Review by QuantumManiac — APPROVED** [review]

**Comment by BluCodeGH** [comment]
Ordered, merging

**Pull request merged**
