### PR TITLE
fat redesign to use PIC18 instead of arduinos

### PR DESCRIPTION
**Pull request by DanielShteinbok**
Main things to double-check:
* pull-up of slave-select lines to 5V; I have no idea if it's the right thing to do to protect/fry expensive components
* the order of pins in the connectors is correct, they connect to the right stuff
* the PWR_EN should be connected to MCLR??
* generally, nothing will cook

Stuff that is very clearly not done, that I did not work on:
* batteries; 12V??
* Some other stuff that I can't think of right now
* Should the valve control be part of the papa board? What's a valve??

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020/5)

### CODE REVIEW

**Comment by LanaTomlin** [comment]
let's conquer the payload 


**Formatting things:**
1. Having one huge sheet in the middle of the schematic makes it kind of difficult to read. Either make the sheet a  lot smaller so all the components aren't at the edge of the schematic or remove the sheet entirely.
2. The SM74611 is missing - this is lowkey my fault. There's a custom payload library file, called "payload2020_custom.lib" which you can add to the schematic by going: Preferences -> Manage Symbol libraries -> Project Specific Libraries -> Little plus symbol Then filling in the nickname (filename) and generic library path which will be (${KIPRJMOD}/payload2020_custom.lib). You can then re-map the symbol by double-clicking on the question marks and selecting the correct symbol from the "browse library" option next to the "Library Reference" box. 
3. There is a random wire going into the battery_management file that isn't connected to anything. This is where the battery will attach to the board, so it should lead to an external connector. If this isn't fixed when the SM74 has the correct library reference, then please fix this. 
4. Net labels should be replaced with Global labels, bc net labels will only connect within the same sheet. 
5. There are loose wires on U2 that do not go anywhere
5. What is SS_MAMA_DUP, and SS_MAMA? Maybe make the labelling a bit clearer.
6. The pull-ups are needed for the SPI lines, but their placement is a bit confusing. I would put them closer either to the connectors or to the pins on the PIC
image
7. This section is a bit of a mess
8. A bunch of components are missing REFDES numbers - you can fix this with the "Annotate Schematic Symbols" button  
9. All input connectors should be in one place, and all output connectors should be in one place. The schematic should flow logically
10. The files names for the sheets are gibberish, meaningful names would be nice
11. CD74HC4050 is also missing the schematic symbol
12. Overall the schematic is kind of messy and difficult to read

**Functionality Things**
1. We only need one CS line (CS, CS_EXT1, CS_EXT2, CS_EXT3, CS_EXT4) We can daisy-chain as explained here: https://en.wikipedia.org/wiki/Serial_Peripheral_Interface#Operation
2. All the valve stuff can be deleted - I don't know what that was for but we do not need it
3. The SD card needs 3.3V but there is no 3.3V line
4. I'm not sure what Adam's intention was with PWR_EN was, you're going to have to ask him, but it's not MCLR. MCLR is needed for the programming header. 
5. Where does PG go, and is it needed?


Let me know if you want me to clarify anything.

**Comment by LanaTomlin** [comment]
1. In the sheet, you don't have to connect the GND pin and +5V pin to the GND and 5V symbols. 
2. Try and keep label names in and outside the sheet the same - there are a bunch of really long label names. If you could shorten those, that would be great.
3. The SD card can be removed. We're going to add a copy of logger board which will serve the function of the SD card. (This means we can also get rid of the 3V3 connector)
4. Is there a reason CLKOUT isn't connected on the MCP25?
5. CAN_INT has THHREEE pull-up resistors. It only needs one
6. Either keep all the resistors and capacitors connected to the MCU, or connect them through labels, doing both is confusing.
7. The programming connector doesn't need to be in the sheet, all connectors should be kept together
8. Messages for questions I think answered last time are still on the sheet - do you need more clarification?
9. There are a lot of random files that are being tracked in Git that do not have names, if they're being used for something, can you make sure the files have names, and if they aren't being used for anything, can you remove them?
10. If you could use wires to stagger the labels on the ICs so everything is more readable, that would be fantastic

As far as I can tell, all your connections look good, but it's hard to read properly. 
The schematic looks a lot better already from last time, but if you can go the extra mile to make it more readable, and nicer to look at that would be amazing. It's a lot easier to find mistakes if everything is formatted nicely and placed logically. Making things cleaner would make a huge difference. 

As always, let me know if you have any questions.

**Comment by DanielShteinbok** [comment]
> Is there a reason CLKOUT isn't connected on the MCP25?
It would make sense that it should be connected, but I'm looking at the [keto board](https://github.com/waterloo-rocketry/canhw/blob/master/picdev/picdev/picdev.pdf) and it seems like they only connect OSC1, not OSC2 (which is what I have elected to do).
As I said, your suggestion of connecting both OSC1 and OSC2 would probably make more sense, but electricity is basically magic anyway. From the [datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/MCP2515-Stand-Alone-CAN-Controller-with-SPI-20001801J.pdf), it seems that OSC1 is actually the MCP2515's external clock input, which is how I'm using it (it's connected to the crystal). It is entirely possible that either the label on the keto board is misleading, or I have a deep misunderstanding of the Art.

**Comment by DanielShteinbok** [comment]
> Try and keep label names in and outside the sheet the same - there are a bunch of really long label names. If you could shorten those, that would be great.

I have changed the net labels in the parent sheet to make them the same as the hierarchical labels, and I have somewhat shortened the other net labels that you probably had a problem with. However, they're still somewhat long--these are the shortest labels that my NPC imagination could ideate such that they are still descriptive. The reason for this is that these are the connections used in daisy-chaining a whole bunch of components; so rather than use numbers/letters or something (which I actually __could__ do--let me know if you would prefer that and I'll make the change), I used something like `[input]_I_[output]_O`. The daisy chain order is as follows:
```
MCP_MOSI -----> MAMA1 ------> MAMA1_O_MAMA2_I --------> MAMA2 ----------> PIC_MISO
```
As I said above, if a different labeling convention would be preferred, let me know. I should probably do my due diligence and attend Electrical meetings before making such judgement calls anyway, which I will do.

**Comment by DanielShteinbok** [comment]
> CD74HC4050 is also missing the schematic symbol

This is from an older review, but I'm pretty sure I never added it. Is this still needed/relevant? What is this for?

**Review by LanaTomlin — COMMENTED** [review]
Overall this looks great!
Some small comments
1. PG pin is not connected
2. Programming connector is missing a REFDES
3. The uneven spacing of the labels is kind of messy, but I get why you did it. So your choice on that one.
4. C10 is missing a value

That's all I've got.

**Comment by LanaTomlin** [comment]
> > CD74HC4050 is also missing the schematic symbol
> 
> This is from an older review, but I'm pretty sure I never added it. Is this still needed/relevant? What is this for?

I do not think CD74HC4050 exists anymore, so you do not need to address this.

**Comment by LanaTomlin** [comment]
> > Is there a reason CLKOUT isn't connected on the MCP25?
> 
> It would make sense that it should be connected, but I'm looking at the [keto board](https://github.com/waterloo-rocketry/canhw/blob/master/picdev/picdev/picdev.pdf) and it seems like they only connect OSC1, not OSC2 (which is what I have elected to do).
> As I said, your suggestion of connecting both OSC1 and OSC2 would probably make more sense, but electricity is basically magic anyway. From the [datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/MCP2515-Stand-Alone-CAN-Controller-with-SPI-20001801J.pdf), it seems that OSC1 is actually the MCP2515's external clock input, which is how I'm using it (it's connected to the crystal). It is entirely possible that either the label on the keto board is misleading, or I have a deep misunderstanding of the Art.

What you have is correct - I misunderstood what "clockout" was doing. Sorry about that.


Also, I forgot to mention this when I left my review, but the folder name "Main_Control_Board" is out of date - might want to rename it to papa board.

**Comment by DanielShteinbok** [comment]
> That's all I've got.

WOOHOO! Methinks the schematic is finally complete!

**Comment by LanaTomlin** [comment]
Hello, I just noticed - the point of the SLEEP_5V is that it the PIC18 will run on that separate voltage line - and if the rocket CANBUS gives a message to turn the system on, the whole system gets turned on (using PWR_EN) and +5V gets connected to the rest of the system. So the PIC18 and the CAN controller for the rocket canbus need to be connected to SLEEP_5V, not +5V

**Pull request merged**
